import logging
from abc import ABC
from typing import Any, Dict, List, Optional

from pydantic import Field
from celofast.services.semantic_layer_client import ExternalAsyncClient
from python_core_internal_client import AsyncClient, PythonCoreBaseEnum, PythonCoreBaseModel

logger = logging.getLogger("python_core_internal_client.phoenix")

JsonNode = Any


class ScopeType(PythonCoreBaseEnum):
    DISABLED = "DISABLED"


class MetadataType(PythonCoreBaseEnum):
    KPI = "KPI"
    DEFAULT_TARGET = "DEFAULT_TARGET"
    RECORD = "RECORD"
    VARIABLE = "VARIABLE"
    ACTIVITY = "ACTIVITY"
    FILTER = "FILTER"
    ACTION = "ACTION"
    ANOMALY = "ANOMALY"
    ATTRIBUTE = "ATTRIBUTE"
    NEW_ATTRIBUTE = "NEW_ATTRIBUTE"
    AUGMENTED_ATTRIBUTE = "AUGMENTED_ATTRIBUTE"
    AUGMENTED_ATTRIBUTE_V2 = "AUGMENTED_ATTRIBUTE_V2"
    PRIORITY = "PRIORITY"
    FLAG = "FLAG"
    EVENT_LOG = "EVENT_LOG"
    DATA_TRIGGER = "DATA_TRIGGER"
    TRIGGER_FILTER = "TRIGGER_FILTER"
    TRIGGER_COLUMN = "TRIGGER_COLUMN"
    TRIGGER = "TRIGGER"


class ColumnValue(PythonCoreBaseModel):
    column_name: Optional["str"] = Field(None, alias="columnName")
    value: Optional["Any"] = Field(None, alias="value")


class AttributeMetadata(PythonCoreBaseModel):
    auto_generated: Optional["bool"] = Field(None, alias="autoGenerated")
    column_type: Optional["str"] = Field(None, alias="columnType")
    custom_attributes: Optional["JsonNode"] = Field(None, alias="customAttributes")
    description: Optional["str"] = Field(None, alias="description")
    display_name: Optional["str"] = Field(None, alias="displayName")
    filter_ids: Optional["List[Optional[str]]"] = Field(None, alias="filterIds")
    format: Optional["str"] = Field(None, alias="format")
    id: Optional["str"] = Field(None, alias="id")
    internal_note: Optional["str"] = Field(None, alias="internalNote")
    pql: Optional["str"] = Field(None, alias="pql")
    scope: Optional["ScopeType"] = Field(None, alias="scope")
    short_display_name: Optional["str"] = Field(None, alias="shortDisplayName")
    type_: Optional["MetadataType"] = Field(None, alias="type")
    unit: Optional["str"] = Field(None, alias="unit")


class RecordAugmentedAttribute(PythonCoreBaseModel):
    augmented_attribute_id: Optional["str"] = Field(None, alias="augmentedAttributeId")
    record_metadata_id: Optional["str"] = Field(None, alias="recordMetadataId")


class AugmentedAttributeDataTransferRequest(PythonCoreBaseModel):
    from_record_augmented_attribute: Optional["RecordAugmentedAttribute"] = Field(
        None, alias="fromRecordAugmentedAttribute"
    )
    knowledge_model_key: Optional["str"] = Field(None, alias="knowledgeModelKey")
    to_augmented_attribute_id: Optional["str"] = Field(None, alias="toAugmentedAttributeId")


class AugmentedAttributeValue(PythonCoreBaseModel):
    augmented_attribute_id: Optional["str"] = Field(None, alias="augmentedAttributeId")
    key_column_values: Optional["List[Optional[ColumnValue]]"] = Field(None, alias="keyColumnValues")
    knowledge_model_key: Optional["str"] = Field(None, alias="knowledgeModelKey")
    value: Optional["str"] = Field(None, alias="value")


class AugmentedAttributeValueUpdateRequest(PythonCoreBaseModel):
    augmented_attribute_value: Optional["AugmentedAttributeValue"] = Field(None, alias="augmentedAttributeValue")
    request_id: Optional["str"] = Field(None, alias="requestId")


class AugmentedAttributeValueUpdateResponse(PythonCoreBaseModel):
    errors: Optional["List[Optional[str]]"] = Field(None, alias="errors")
    request_id: Optional["str"] = Field(None, alias="requestId")


class PhoenixClientBase(ABC):
    client: AsyncClient

    def __init__(self, base_url: str, **kwargs: Any) -> None:
        self.client = AsyncClient(base_url=base_url, **kwargs)

    async def post_api_augmented_attributes_values(
        self,
        request_body: List[AugmentedAttributeValueUpdateRequest],
        draft_mode: Optional["bool"] = None,
        **kwargs: Any,
    ) -> List[Optional[AugmentedAttributeValueUpdateResponse]]:
        params: Dict[str, Any] = {}
        if draft_mode is not None:
            if isinstance(draft_mode, PythonCoreBaseModel):
                params.update(draft_mode.json_dict(by_alias=True))
            elif isinstance(draft_mode, dict):
                params.update(draft_mode)
            else:
                params["draftMode"] = draft_mode
        return await self.client.request(
            method="POST",
            url="/api/augmented-attributes/values",
            params=params,
            request_body=request_body,
            parse_json=True,
            type_=List[Optional[AugmentedAttributeValueUpdateResponse]],
            **kwargs,
        )


class PhoenixClient(PhoenixClientBase):
    pass


class PhoenixExternalClient(PhoenixClientBase):
    def __init__(self, base_url: str, headers: dict[str, str], **kwargs: Any) -> None:
        self.client = ExternalAsyncClient(base_url=base_url, headers=headers, **kwargs)

