import importlib.util
import json
import sys
from dataclasses import FrozenInstanceError

import pytest

from celofast.sdk import Capture, Source
from celofast.sdk.generate import generate
from celofast.sdk.objects import Attribute, GenericKnowledgeObject


def load_generated(capture, tmp_path):
    files = generate(capture)
    for name, data in files.items():
        (tmp_path / name).write_bytes(data)
    spec = importlib.util.spec_from_file_location(
        "sdk_fixture", tmp_path / "__init__.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module.km, json.loads(files["schema.json"])


def test_module_reload_preserves_old_hierarchy_after_definition_removal(
    tmp_path, monkeypatch
):
    source = Source(tenant_id="t", space_id="s", package_id="p", key="km", mode="draft")
    before = Capture.create(
        source,
        {
            "kpis": [
                {
                    "id": "Value",
                    "pql": "41",
                    "columnType": "INTEGER",
                    "parameters": [{"id": "OldParameter"}],
                },
                {"id": "Removed", "pql": "1", "columnType": "INTEGER"},
            ]
        },
    )
    after = Capture.create(
        source,
        {
            "kpis": [
                {"id": "Value", "pql": "99", "columnType": "INTEGER", "parameters": []},
            ]
        },
    )
    name = "sdk_reload_fixture"
    package = tmp_path / name
    package.mkdir()
    monkeypatch.syspath_prepend(str(tmp_path))
    for filename, data in generate(before).items():
        (package / filename).write_bytes(data)
    module = importlib.import_module(name)
    try:
        old = module.km
        old_namespace = old.kpis
        for filename, data in generate(after).items():
            (package / filename).write_bytes(data)
        importlib.invalidate_caches()
        new = importlib.reload(module).km
        assert new.kpis.value.pql == "99"
        assert new.kpis.value.metadata["parameters"] == ()
        with pytest.raises(KeyError):
            new.kpis["Removed"]
        for namespace in (old_namespace, old.kpis):
            assert namespace.value.pql == "41"
            assert namespace.value.parameters.old_parameter.id == "OldParameter"
            assert namespace.removed.pql == "1"
    finally:
        sys.modules.pop(name, None)


@pytest.mark.parametrize("mode", ["draft", "published"])
def test_every_source_id_and_metadata_survives_unknown_nested_content(tmp_path, mode):
    source = Source(tenant_id="t", space_id="s", package_id="p", key="km", mode=mode)
    content = {
        "id": "root",
        "metadata": {"key": "km", "version": "1"},
        "records": [
            {
                "id": "Plant",
                "origin": "INHERITED",
                "autoGenerated": True,
                "identifier": {"id": "Identifier", "pql": '"Plant"."ID"'},
                "attributes": [
                    {
                        "id": "Number",
                        "columnType": "STRING",
                        "pql": "'one'",
                        "validationStatusType": "OPEN",
                        "validationStatus": None,
                    }
                ],
                "newAttributes": [{"id": "New", "columnType": "FLOAT"}],
                "augmentedAttributes": [{"id": "Augmented", "columnType": "DATE"}],
            }
        ],
        "kpis": [
            {
                "id": "Value",
                "parameters": [{"id": "P", "defaultValue": "2"}],
                "targets": [{"id": "T", "value": 10}],
                "breakdowns": [{"id": "B"}],
            }
        ],
        "futureCategory": [
            [{"id": "deep", "unknown": {"ordered": [3, 1], "null": None}}]
        ],
        "customObjects": [
            {"description": "An object without an ID", "payload": {"plain": True}}
        ],
    }
    for category in (
        "filters",
        "variables",
        "activities",
        "actions",
        "anomalies",
        "eventLogs",
        "ruleGroups",
        "visualMappings",
    ):
        content[category] = [
            {"id": category + "_item", "newMetadata": {"preserve": True}}
        ]
    capture = Capture.create(source, content)
    root, manifest = load_generated(capture, tmp_path)

    def objects(value, path=()):
        if isinstance(value, dict):
            if "id" in value:
                yield path, value
            for key, child in value.items():
                yield from objects(child, (*path, key))
        elif isinstance(value, list):
            for index, child in enumerate(value):
                segment = (
                    child["id"]
                    if isinstance(child, dict) and isinstance(child.get("id"), str)
                    else index
                )
                yield from objects(child, (*path, segment))

    expected = dict(objects(capture.to_dict()))
    actual = {
        tuple(entry["path"]): entry
        for entry in manifest["objects"]
        if entry["id"] is not None
    }
    assert set(actual) == set(expected)
    for path, entry in actual.items():
        obj = root
        for symbol in entry["python"].split(".")[1:]:
            obj = getattr(obj, symbol)
        assert obj.id == expected[path]["id"]
        assert json.loads(json.dumps(obj.metadata, default=dict)) == expected[path]
    assert root.future_category.item_0.deep.id == "deep"
    assert root.custom_objects.item_0.metadata["payload"]["plain"] is True


def test_names_cannot_shadow_runtime_and_collisions_remain_discoverable(tmp_path):
    source = Source(tenant_id="t", space_id="s", package_id="p", key="km", mode="draft")
    ids = [
        "NumberName",
        "number_name",
        "class",
        "1first",
        "日本",
        "metadata",
        "capture",
        "path",
        "_members",
    ]
    capture = Capture.create(
        source,
        {
            "namespace": [{"id": "Entry", "children": [{"id": "Nested"}]}],
            "record": {"id": "Plain", "children": [{"id": "Nested"}]},
            "records": [
                {
                    "id": "Plant",
                    "attributes": [
                        {"id": id_, "columnType": "STRING", "pql": "'value'"}
                        for id_ in ids
                    ],
                }
            ],
        },
    )
    root, manifest = load_generated(capture, tmp_path)
    assert {item.id for item in root.records.plant.attributes} == set(ids)
    assert root.records.plant.attributes["class"].id == "class"
    assert root.records.plant.attributes["metadata"].pql == "'value'"
    assert root.namespace.entry.children.nested.id == "Nested"
    mappings = [entry["python"] for entry in manifest["objects"]]
    assert len(mappings) == len(set(mappings))


def test_generated_package_imports_offline_with_complete_discoverable_objects(tmp_path):
    capture = Capture.create(
        Source(
            tenant_id="tenant",
            space_id="space",
            package_id="package",
            key="inventory-km",
            mode="draft",
        ),
        {
            "records": [
                {
                    "id": "O_CELONIS_PLANT",
                    "type": "RECORD",
                    "attributes": [
                        {
                            "id": "NumberNameConcat",
                            "columnType": "string",
                            "pql": '\n"Plant"."Number" || \' - \' || "Plant"."Name"',
                            "description": 'Quotes """ and Unicode café',
                            "unknown": {"enabled": True},
                        },
                        {
                            "id": "NumberFormatted",
                            "columnType": "string",
                            "pql": '"Plant"."Number"',
                        },
                    ],
                }
            ],
            "futureObjects": [{"id": "class", "definition": {"preserved": [3, 1]}}],
        },
    )
    files = generate(capture)
    assert files == generate(capture)
    for name, data in files.items():
        (tmp_path / name).write_bytes(data)
    spec = importlib.util.spec_from_file_location(
        "generated_inventory", tmp_path / "__init__.py"
    )
    module = importlib.util.module_from_spec(spec)
    # dataclasses use the module registry to resolve postponed annotations.
    import sys

    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
        km = module.km
        plant = km.records.o_celonis_plant
        attr = plant.attributes.number_name_concat
        assert isinstance(attr, Attribute)
        assert attr.id == "NumberNameConcat"
        assert attr.column_type == "string"
        assert attr.pql.startswith('\n"Plant"')
        assert attr.metadata["unknown"]["enabled"] is True
        assert plant.attributes["NumberNameConcat"] == attr
        assert len(list(plant.attributes)) == 2
        assert isinstance(km.future_objects.class_, GenericKnowledgeObject)
        for obj in (km, plant, attr, plant.attributes):
            with pytest.raises(FrozenInstanceError):
                obj.unexpected_mutation = 1
        assert any(
            entry["id"] == "class"
            for entry in json.loads(files["schema.json"])["objects"]
        )
    finally:
        sys.modules.pop(spec.name, None)
