"""Case variants share a field only when their expressions also match."""

import pytest

from celofast.sdk import Capture
from celofast.sdk.generate import generate
from celofast.sdk.mapping import normalize

from objects_fixture import SOURCE, attribute


def model(attributes):
    return Capture(source=SOURCE, definition={"records": [{
        "id": "O_VENDOR", "pql": "o_Vendor",
        "identifier": {"pql": '"o_Vendor"."ID"'},
        "attributes": [attribute("ID", '"o_Vendor"."ID"'), *attributes],
    }]})


@pytest.mark.parametrize("name", ["City", "Country", "CurrentValuatedStockQuantity"])
@pytest.mark.parametrize("reverse", [False, True])
def test_case_variants_share_one_field_without_skip_diagnostics(name, reverse):
    attrs = [
        attribute(name.upper(), f'"o_Vendor"."{name}"\n'),
        attribute(name, f'"o_Vendor"."{name}"'),
    ]
    cap = model(list(reversed(attrs)) if reverse else attrs)
    result = normalize(cap)
    assert not result.diagnostics
    assert len(result.objects[0].fields) == 2
    field = result.objects[0].fields[1]
    assert field.attribute_id == name
    assert field.name == {"City": "city", "Country": "country",
                          "CurrentValuatedStockQuantity": "current_valuated_stock_quantity"}[name]
    assert "same expression as" not in generate(cap)["objects.py"].decode()


def test_uppercase_id_uses_column_spelling_without_column_name_metadata():
    cap = model([attribute("CURRENTVALUATEDSTOCKQUANTITY", '"o_Vendor"."CurrentValuatedStockQuantity"')])
    assert normalize(cap).objects[0].fields[1].name == "current_valuated_stock_quantity"


def test_case_variants_with_different_expressions_are_not_collapsed():
    result = normalize(model([
        attribute("CITY", '"o_Vendor"."City"'),
        attribute("City", '"o_Vendor"."OtherCity"'),
    ]))
    assert len(result.objects[0].fields) == 3
    assert {field.attribute_id for field in result.objects[0].fields} == {"ID", "CITY", "City"}


def test_distinct_attribute_names_survive_shared_expressions_regardless_of_source():
    cap = model([
        attribute("CITY", '"o_Vendor"."City"', attributeSource="DATA_MODEL", autoGenerated=True),
        attribute("SupplierCity", '"o_Vendor"."City"', attributeSource="KNOWLEDGE_MODEL"),
    ])
    result = normalize(cap)
    assert [field.name for field in result.objects[0].fields] == ["id", "city", "supplier_city"]
    assert not result.diagnostics


@pytest.mark.parametrize("reverse", [False, True])
def test_km_attribute_is_not_replaced_by_generated_data_model_column(reverse):
    expression = '"o_Line"."CancellationReason"'
    attributes = [
        attribute("CANCELLATIONREASON", expression, attributeSource="DATA_MODEL", autoGenerated=True),
        attribute("RejectionReasonFormatted", expression + "\n", None,
                  attributeSource="KNOWLEDGE_MODEL", displayName="Rejection Reason",
                  description="Indicates if (and why) the line has been rejected."),
    ]
    cap = Capture(source=SOURCE, definition={"records": [{
        "id": "O_LINE", "pql": "o_Line",
        "attributes": [attribute("ID", '"o_Line"."ID"'),
                       *(reversed(attributes) if reverse else attributes)],
    }]}, tables={"o_Line": {"primary_key": ["ID"], "columns": {
        "ID": "STRING", "CancellationReason": "STRING",
    }}})
    result = normalize(cap)
    assert not result.diagnostics
    fields = {field.attribute_id: field for field in result.objects[0].fields}
    assert set(fields) == {"ID", "CANCELLATIONREASON", "RejectionReasonFormatted"}
    field = fields["RejectionReasonFormatted"]
    assert (field.name, field.value_type, field.display_name) == ("rejection_reason_formatted", "str", "Rejection Reason")
    assert field.description == attributes[1]["description"]
    assert "rejection_reason_formatted: str | None" in generate(cap)["objects.py"].decode()


@pytest.mark.parametrize("reverse", [False, True])
def test_column_aliases_do_not_change_keys_or_automatic_links(reverse):
    def ordered(items):
        return list(reversed(items)) if reverse else items

    cap = Capture(source=SOURCE, definition={"records": [
        {"id": "O_PLANT", "pql": "o_Plant", "attributes": ordered([
            attribute("PlantKey", '"o_Plant"."ID"'), attribute("ID", '"o_Plant"."ID"'),
        ])},
        {"id": "O_LINE", "pql": "o_Line", "attributes": [
            attribute("ID", '"o_Line"."ID"'), *ordered([
                attribute("SiteReference", '"o_Line"."Plant_ID"'),
                attribute("PLANT_ID", '"o_Line"."Plant_ID"'),
            ]),
        ]},
    ]}, tables={
        "o_Plant": {"primary_key": ["ID"], "columns": {"ID": "STRING"}},
        "o_Line": {"primary_key": ["ID"], "columns": {"ID": "STRING", "Plant_ID": "STRING"}},
    }, joins=[{"one": "o_Plant", "many": "o_Line", "columns": [["ID", "Plant_ID"]]}])
    result = normalize(cap)
    assert not result.diagnostics
    plant = next(spec for spec in result.objects if spec.record_id == "O_PLANT")
    line = next(spec for spec in result.objects if spec.record_id == "O_LINE")
    assert plant.key == ("id",)
    assert line.links[0].on == (("plant_id", "id"),)
    assert plant.links[0].on == (("id", "plant_id"),)
