"""Deterministic object SDK packages from a KM capture and an object mapping.

Each identified record produces a definition class (``PlantDefinition``), a
value class (``Plant``), and, when relationships are declared, a typed links
class (``PlantLinks``). The package root exports the value classes and ``km``,
the registry passed to ``cf.km(...)``.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any

from celofast.sdk.capture import Capture
from celofast.sdk.loading import RUNTIME_API_VERSION, capture_digest
from celofast.sdk.mapping import MappingConfig, ModelSpec, ObjectSpec, normalize

GENERATOR_VERSION = 9
PACKAGE_FILES = (
    "__init__.py",
    "definitions.py",
    "objects.py",
    "links.py",
    "capture.json",
    "schema.json",
    "py.typed",
)
_HEADER = "# Generated by celofast km pull. Do not edit.\nfrom __future__ import annotations\n\n"


# Qualified temporal types keep a business field named "date" from shadowing
# its own annotation inside the generated class body.
_TYPES = {"date": "_dt.date", "datetime": "_dt.datetime"}


def _annotation(value_type: str, key: bool) -> str:
    type_ = _TYPES.get(value_type, value_type)
    return type_ if key else f"{type_} | None"


def _key_annotation(spec: ObjectSpec) -> str:
    types = [
        _annotation(next(f for f in spec.fields if f.name == name).value_type, True)
        for name in spec.key
    ]
    return types[0] if len(types) == 1 else f"tuple[{', '.join(types)}]"


def _docstring(text: str, indent: str = "    ") -> str:
    return f"{indent}{text!r}\n"


def _definitions(model: ModelSpec, capture: Capture) -> str:
    lines = [
        _HEADER,
        "import datetime as _dt\n",
        "from dataclasses import dataclass\n",
        "from pathlib import Path\n",
        "from typing import ClassVar\n\n",
        "import celofast.sdk.definitions as _d\n",
        "from celofast.sdk.loading import load_capture\n\n",
        "_capture = load_capture(\n",
        '    Path(__file__).with_name("capture.json"),\n',
        f"    runtime_api={RUNTIME_API_VERSION},\n",
        f"    digest={capture_digest(capture)!r},\n",
        ")\n",
    ]
    for spec in model.objects:
        lines.append(f"\n\n@dataclass(frozen=True, kw_only=True)\nclass {spec.class_name}Definition(_d.ObjectDefinition):\n")
        lines.append(_docstring(spec.description))
        for field in spec.fields:
            lines.append(f"    {field.name}: _d.Field[{_annotation(field.value_type, field.key)}]\n")
            lines.append(_docstring(field.attribute_id))
        lines.append(f"    _members: ClassVar[tuple[str, ...]] = {tuple(f.name for f in spec.fields)!r}\n")
        lines.append(f"    _key: ClassVar[tuple[str, ...]] = {spec.key!r}\n")
        lines.append("    _links: ClassVar[tuple[_d.LinkDefinition, ...]] = (\n")
        for link in spec.links:
            lines.append(
                f"        _d.LinkDefinition(name={link.name!r}, target={link.target!r}, "
                f"cardinality={link.cardinality!r}, on={link.on!r}),\n"
            )
        lines.append("    )\n")
    for spec in model.objects:
        lines.append(f"\n\n_{spec.class_name} = {spec.class_name}Definition(\n")
        lines.append(f"    capture=_capture,\n    path={spec.path!r},\n")
        for field in spec.fields:
            lines.append(
                f"    {field.name}=_d.Field(capture=_capture, path={field.path!r}, "
                f"name={field.name!r}, owner={spec.record_id!r}, "
                f"value_type={field.value_type!r}, nullable={not field.key!r}),\n"
            )
        lines.append(")\n")
    return "".join(lines)


def _objects(model: ModelSpec) -> str:
    lines = [
        _HEADER,
        "import datetime as _dt\n",
        "from dataclasses import dataclass\n",
        "from typing import ClassVar\n\n",
        "import celofast.sdk.objects as _o\n\n",
        "from . import definitions as _defs\n",
        "from . import links as _links\n",
    ]
    for spec in model.objects:
        lines.append(f"\n\n@dataclass(frozen=True, kw_only=True)\nclass {spec.class_name}(_o.Object):\n")
        lines.append(_docstring(spec.description))
        lines.append(f"    key: {_key_annotation(spec)}\n")
        for field in spec.fields:
            lines.append(f"    {field.name}: {_annotation(field.value_type, field.key)}\n")
        lines.append(f"\n    fields: ClassVar[_defs.{spec.class_name}Definition] = _defs._{spec.class_name}\n")
        if spec.links:
            lines.append(
                f"    relations: ClassVar[_links.{spec.class_name}Relations] = "
                f"_links.{spec.class_name}Relations()\n"
            )
            lines.append(
                "\n    @property\n"
                f"    def links(self) -> _links.{spec.class_name}Links:\n"
                f"        return _links.{spec.class_name}Links(self)\n"
            )
    names = ", ".join(spec.class_name for spec in model.objects)
    lines.append(
        f"\n\nkm = _o.ObjectModel(capture=_defs._capture, objects=({names}{',' if len(model.objects) == 1 else ''}))\n"
    )
    return "".join(lines)


def _links(model: ModelSpec) -> str:
    lines = [_HEADER, "import celofast.sdk.objects as _o\n\n", "from . import objects as _objects\n"]
    classes = {spec.record_id: spec.class_name for spec in model.objects}
    for spec in model.objects:
        if not spec.links:
            continue
        lines.append(f"\n\nclass {spec.class_name}Links(_o.Links):\n")
        lines.append(_docstring(f"Relationships of {spec.class_name}; every access is explicit."))
        for link in spec.links:
            target = f"_objects.{classes[link.target]}"
            if link.cardinality == "one":
                returns, call = f"_o.ToOne[{target}]", "_one"
            else:
                returns, call = f"_o.ObjectCollection[{target}]", "_many"
            lines.append(
                "\n    @property\n"
                f"    def {link.name}(self) -> {returns}:\n"
                f"        return self.{call}({link.name!r}, {target})\n"
            )
        lines.append(f"\n\nclass {spec.class_name}Relations(_o.Relations):\n")
        lines.append(_docstring(f"Relationship predicates for filtering {spec.class_name} objects."))
        for link in spec.links:
            target = f"_objects.{classes[link.target]}"
            source = f"_objects.{spec.class_name}"
            if link.cardinality == "one":
                returns, call = f"_o.ToOneRelation[{target}]", "_one"
            else:
                returns, call = f"_o.ToManyRelation[{target}]", "_many"
            lines.append(
                "\n    @property\n"
                f"    def {link.name}(self) -> {returns}:\n"
                f"        return self.{call}({link.name!r}, {source}, {target})\n"
            )
    return "".join(lines)


def _init(model: ModelSpec) -> str:
    names = [spec.class_name for spec in model.objects]
    imports = "".join(f"    {name},\n" for name in names)
    return (
        _HEADER
        + f"from .objects import (\n{imports}    km,\n)\n\n"
        + f"__all__ = {[*names, 'km']!r}\n"
    )


def generate(
    capture: Capture, mapping: Mapping[str, Any] | MappingConfig | None = None
) -> dict[str, bytes]:
    """Render a self-contained typed package without touching the filesystem."""
    model = normalize(capture, mapping)
    modules = {
        "__init__.py": _init(model),
        "definitions.py": _definitions(model, capture),
        "objects.py": _objects(model),
        "links.py": _links(model),
    }
    for name, source in modules.items():
        compile(source, f"<generated {name}>", "exec")
    inventory: list[dict[str, Any]] = []
    for spec in model.objects:
        inventory.append({"path": list(spec.path), "id": spec.record_id, "python": spec.class_name})
        for field in spec.fields:
            inventory.append(
                {
                    "path": list(field.path),
                    "id": field.attribute_id,
                    "python": f"{spec.class_name}.{field.name}",
                    "type": field.value_type,
                    "key": field.key,
                }
            )
        for link in spec.links:
            inventory.append(
                {
                    "path": [*spec.path, "links", link.name],
                    "id": link.name,
                    "python": f"{spec.class_name}.links.{link.name}",
                    "target": link.target,
                    "cardinality": link.cardinality,
                }
            )
    manifest = {
        "managed_by": "celofast.km",
        "runtime_api": RUNTIME_API_VERSION,
        "generator_version": GENERATOR_VERSION,
        "format_version": capture.format_version,
        "source": capture.source.model_dump(),
        "fingerprint": capture.fingerprint,
        "mapping": model.mapping.model_dump(mode="json", by_alias=True, exclude_defaults=True),
        "excluded": list(model.excluded),
        "objects": inventory,
        "diagnostics": list(model.diagnostics),
    }
    files = {name: source.encode("utf-8") for name, source in modules.items()}
    files["capture.json"] = capture.to_json().encode("utf-8")
    files["schema.json"] = (
        json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    ).encode("utf-8")
    files["py.typed"] = b""
    return files
