"""Deterministic object SDK packages from a KM capture and an object mapping.

Each object type produces a definition class (``PlantDefinition``, its typed
fields), a value class (``Plant``, one loaded object), and, when it has
relationships, a links class (``PlantLinks``). All live in ``objects.py``; the
package root exports the value classes and ``km``, the registry passed to
``cf.km(...)``.

The package is self-contained Python: field expressions, source identity, and
metadata are written as literals, so a KM change appears as a readable diff of
the generated code.
"""

from __future__ import annotations

import re
from typing import Any

from celofast.sdk.capture import Capture
from celofast.sdk.loading import RUNTIME_API_VERSION
from celofast.sdk.mapping import MappingInput, ModelSpec, ObjectSpec, normalize

PACKAGE_FILES = ("__init__.py", "objects.py", "py.typed")
MARKER = "__celofast__"
HEADER = "# Generated by celofast km pull. Do not edit.\n"
_COMMENTS = re.compile(r"--.*?$|/\*[\s\S]*?\*/", re.MULTILINE)
_VARIABLES = re.compile(r"\$\{(\w+)\}")
# Qualified temporal types keep a business field named "date" from shadowing
# its own annotation inside the generated class body.
_TYPES = {"date": "_dt.date", "datetime": "_dt.datetime"}


def _variables(model: ModelSpec) -> tuple[str, ...]:
    """``${name}`` placeholders in generated expressions, outside comments."""
    return tuple(sorted({
        name
        for spec in model.objects
        for field in spec.fields
        for name in _VARIABLES.findall(_COMMENTS.sub("", field.expression))
    }))


def _annotation(value_type: str, key: bool) -> str:
    type_ = _TYPES.get(value_type, value_type)
    return type_ if key else f"{type_} | None"


def _definition(spec: ObjectSpec) -> list[str]:
    metadata = {"displayName": spec.display_name, "description": spec.record_description}
    lines = [
        f"\n\nclass {spec.class_name}Definition(_d.ObjectDefinition):\n",
        f"    {spec.description!r}\n\n",
        f"    _object_type = {spec.record_id!r}\n",
        f"    _table = {spec.table!r}\n",
        f"    _key = {spec.key!r}\n",
        f"    _metadata = {metadata!r}\n\n",
    ]
    for field in spec.fields:
        kind = "DateTimeField" if field.value_type == "datetime" else "Field"
        extra = "".join(
            f", {name}={value!r}"
            for name, value in (("display_name", field.display_name), ("description", field.description))
            if value is not None
        )
        lines.append(
            f"    {field.name}: _d.{kind}[{_annotation(field.value_type, field.key)}] = "
            f"_d.{kind}({field.attribute_id!r}, {field.expression!r}, {field.value_type!r}{extra})\n"
        )
    return lines


def _value(spec: ObjectSpec) -> list[str]:
    types = {field.name: field.value_type for field in spec.fields}
    keys = [_annotation(types[name], True) for name in spec.key]
    key = keys[0] if len(keys) == 1 else f"tuple[{', '.join(keys)}]"
    lines = [
        f"\n\n@dataclass(frozen=True, kw_only=True)\nclass {spec.class_name}(_o.Object):\n",
        f"    {spec.description!r}\n\n",
        f"    key: {key}\n",
        *(f"    {field.name}: {_annotation(field.value_type, field.key)}\n" for field in spec.fields),
        f"\n    fields: ClassVar[{spec.class_name}Definition] = {spec.class_name}Definition()\n",
    ]
    if spec.links:
        lines += [
            f"    relations: ClassVar[type[{spec.class_name}Links]]\n",
            "\n    @property\n",
            f"    def links(self) -> {spec.class_name}Links:\n",
            f"        return {spec.class_name}Links(self)\n",
        ]
    return lines


def _links(spec: ObjectSpec, classes: dict[str, str]) -> list[str]:
    lines = [
        f"\n\nclass {spec.class_name}Links(_o.Links, source={spec.class_name}):\n",
        f"    {f'Relationships of {spec.class_name}.'!r}\n\n",
    ]
    for link in spec.links:
        kind = "ToOneRelation" if link.cardinality == "one" else "ToManyRelation"
        lines.append(
            f"    {link.name} = _o.{kind}({classes[link.target]}, on={link.on!r}, join={link.join!r})\n"
        )
    return lines


def _objects(model: ModelSpec, capture: Capture) -> str:
    data_model_id = capture.definition.get("dataModelId")
    lines = [
        HEADER,
        "from __future__ import annotations\n\n",
        "import datetime as _dt\n",
        "from dataclasses import dataclass\n",
        "from typing import ClassVar\n\n",
        "import celofast.sdk.definitions as _d\n",
        "import celofast.sdk.objects as _o\n",
        "from celofast.sdk.capture import Source as _Source\n",
        "from celofast.sdk.loading import require_runtime\n\n",
        f"require_runtime({RUNTIME_API_VERSION})\n",
    ]
    if model.diagnostics:
        lines.append("\n# Not generated:\n")
        lines.extend(f"#   {note}\n" for note in model.diagnostics)
    for spec in model.objects:
        lines += _definition(spec) + _value(spec)
    classes = {spec.record_id: spec.class_name for spec in model.objects}
    for spec in model.objects:
        if spec.links:
            lines += _links(spec, classes)
    names = "".join(f"        {spec.class_name},\n" for spec in model.objects)
    lines += [
        "\n\nkm = _o.ObjectModel(\n",
        "    source=_Source(\n",
        *(f"        {name}={value!r},\n" for name, value in capture.source.model_dump().items()),
        "    ),\n",
        f"    data_model_id={data_model_id if isinstance(data_model_id, str) else None!r},\n",
        f"    variables={_variables(model)!r},\n",
        f"    objects=(\n{names}    ),\n",
        ")\n",
    ]
    return "".join(lines)


def stamp(capture: Capture) -> dict[str, Any]:
    """Ownership and provenance recorded in every generated ``__init__.py``.

    The installer reads it to recognize its own output and to refuse replacing
    a package pulled from a different KM.
    """
    return {"managed_by": "celofast.km", "source": capture.source.model_dump()}


def _init(model: ModelSpec, capture: Capture) -> str:
    names = [spec.class_name for spec in model.objects]
    imports = "".join(f"    {name},\n" for name in names)
    return (
        HEADER
        + f"from .objects import (\n{imports}    km,\n)\n\n"
        + f"__all__ = {[*names, 'km']!r}\n\n"
        + "# Identifies this directory as generated output.\n"
        + f"{MARKER} = {stamp(capture)!r}\n"
    )


def generate(capture: Capture, mapping: MappingInput = None) -> dict[str, bytes]:
    """Render a self-contained Python package without touching the filesystem."""
    model = normalize(capture, mapping)
    modules = {"__init__.py": _init(model, capture), "objects.py": _objects(model, capture)}
    for name, source in modules.items():
        compile(source, f"<generated {name}>", "exec")
    files = {name: source.encode("utf-8") for name, source in modules.items()}
    files["py.typed"] = b""
    return files
