"""Small immutable runtime shared by generated Knowledge Model packages."""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, ClassVar, Generic, TypeVar

from celofast.sdk.capture import Capture
from celofast.types import ResourceMode

if TYPE_CHECKING:
    from celofast.expressions import Predicate

T = TypeVar("T")
Path = tuple[str | int, ...]


@dataclass(frozen=True)
class KnowledgeObject:
    """A definition in one capture. Generated subclasses add concrete children."""

    capture: Capture
    path: Path = ()

    @property
    def metadata(self) -> Mapping[str, Any]:
        value: Any = self.capture.definition
        for segment in self.path:
            if isinstance(value, tuple) and isinstance(segment, str):
                matches = [
                    item
                    for item in value
                    if isinstance(item, Mapping) and item.get("id") == segment
                ]
                if len(matches) != 1:
                    raise KeyError(segment)
                value = matches[0]
            else:
                value = value[segment]
        return value

    @property
    def id(self) -> str | None:
        return self.metadata.get("id")

    @property
    def display_name(self) -> str | None:
        return self.metadata.get("displayName")

    @property
    def short_display_name(self) -> str | None:
        return self.metadata.get("shortDisplayName")

    @property
    def description(self) -> str | None:
        return self.metadata.get("description")

    @property
    def origin(self) -> str | None:
        return self.metadata.get("origin")

    @property
    def source(self) -> str | None:
        return self.metadata.get("attributeSource")

    @property
    def scope(self) -> str | None:
        return self.metadata.get("scope")

    @property
    def auto_generated(self) -> bool | None:
        return self.metadata.get("autoGenerated")

    @property
    def column_type(self) -> str | None:
        return self.metadata.get("columnType")

    @property
    def pql(self) -> str | None:
        return self.metadata.get("pql")


@dataclass(frozen=True)
class Record(KnowledgeObject):
    """Captured record definition, not a materialized data row."""

    # None supports manually constructed records; generated records always
    # declare their stored fields, including an empty tuple for empty records.
    _members: ClassVar[tuple[tuple[str | None, str], ...] | None] = None

    def __iter__(self) -> Iterator[Attribute[Any]]:
        """Iterate all attributes in their captured collection and field order."""
        if self._members is not None:
            for _, name in self._members:
                yield getattr(self, name)
            return
        for collection in ("attributes", "newAttributes", "augmentedAttributes"):
            for index, item in enumerate(self.metadata.get(collection) or ()):
                if isinstance(item, Mapping) and item.get("type") in (None, "ATTRIBUTE"):
                    yield Attribute(self.capture, (*self.path, collection, index))

    def __len__(self) -> int:
        """Count all attributes, including those without a query expression."""
        if self._members is not None:
            return len(self._members)
        return sum(1 for _ in self)

    def __getitem__(self, source_id: str) -> Attribute[Any]:
        """Look up an exact source ID; missing or ambiguous IDs raise KeyError."""
        return self.get_attribute(source_id)

    def get_attribute(
        self, source_id: str, *, collection: str | None = None
    ) -> Attribute[Any]:
        """Look up an ID, optionally scoped to an original capture collection.

        Collection keys are attributes, newAttributes, or augmentedAttributes.
        Generated records return their stored attribute objects.
        """
        matches = [
            attribute for attribute in self
            if attribute.id == source_id
            and (collection is None or attribute.path[-2] == collection)
        ]
        if len(matches) != 1:
            raise KeyError(source_id)
        return matches[0]

    def _query_attributes(self) -> Iterator[Attribute[Any]]:
        """Yield queryable attributes in each captured collection's order."""
        for attribute in self:
            if (
                isinstance(attribute.id, str)
                and attribute.id.strip()
                and isinstance(attribute.pql, str)
                and attribute.pql.strip()
            ):
                yield attribute


@dataclass(frozen=True)
class _Sortable(KnowledgeObject, Generic[T]):
    def asc(self) -> Sort:
        """Order this captured expression from low to high."""
        return Sort(self)

    def desc(self) -> Sort:
        """Order this captured expression from high to low."""
        return Sort(self, ascending=False)


@dataclass(frozen=True)
class Sort:
    """An ordering that retains the captured expression and its source."""

    expression: _Sortable[Any]
    ascending: bool = True


@dataclass(frozen=True)
class Attribute(_Sortable[T]):
    """Captured attribute with a declared value type, possibly nullable in data."""

    def eq(self, value: T | None) -> Predicate:
        """Compare with a Python value; None produces an IS NULL filter."""
        from celofast.expressions import Predicate

        return Predicate.equal(self, value)


@dataclass(frozen=True)
class KPI(_Sortable[T]):
    """Captured KPI, including its definition and associated metadata."""


@dataclass(frozen=True)
class Filter(KnowledgeObject):
    """Captured KM filter definition."""


@dataclass(frozen=True)
class KnowledgeModel(KnowledgeObject):
    """Offline root of captured KM query definitions and metadata."""

    @property
    def input_variables(self) -> Mapping[str, Any] | None:
        """Captured Studio defaults for inspection; execution remains native."""
        return self.capture.input_variables

    @property
    def key(self) -> str:
        return self.capture.source.key

    @property
    def mode(self) -> ResourceMode:
        return self.capture.source.mode


@dataclass(frozen=True)
class Namespace:
    """Generated collection with autocomplete, iteration, and exact-ID lookup."""

    capture: Capture
    path: Path
    _members: ClassVar[tuple[tuple[str | None, str], ...]] = ()

    def __iter__(self) -> Iterator[KnowledgeObject]:
        for _, name in self._members:
            yield getattr(self, name)

    def __len__(self) -> int:
        return len(self._members)

    def __getitem__(self, source_id: str) -> KnowledgeObject:
        matches = [name for id_, name in self._members if id_ == source_id]
        if len(matches) != 1:
            raise KeyError(source_id)
        return getattr(self, matches[0])
