"""Small immutable runtime shared by generated Knowledge Model packages."""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from dataclasses import dataclass, field, replace
from typing import TYPE_CHECKING, Any, ClassVar, Generic, TypeVar

from typing_extensions import Self

from celofast.sdk.capture import Capture
from celofast.types import ResourceMode

if TYPE_CHECKING:
    import pandas as pd
    import pycelonis.pql as pql
    from pycelonis.ems.data_integration.data_model import DataModel
    from pycelonis.ems.studio.content_node.knowledge_model import (
        KnowledgeModel as NativeKnowledgeModel,
    )
    from celofast.builder import Query
    from celofast.expressions import Predicate
    from celofast.resources.augmentation_table import AugmentationTableCollection
    from celofast.resources.knowledge_model import KnowledgeModelHandle

T = TypeVar("T")
Path = tuple[str | int, ...]


@dataclass(frozen=True)
class KnowledgeObject:
    """A definition in one capture. Generated subclasses add concrete children."""

    capture: Capture
    path: Path = ()

    @property
    def metadata(self) -> Mapping[str, Any]:
        value: Any = self.capture.definition
        for segment in self.path:
            if isinstance(value, tuple) and isinstance(segment, str):
                matches = [
                    item
                    for item in value
                    if isinstance(item, Mapping) and item.get("id") == segment
                ]
                if len(matches) != 1:
                    raise KeyError(segment)
                value = matches[0]
            else:
                value = value[segment]
        return value

    @property
    def id(self) -> str | None:
        return self.metadata.get("id")

    @property
    def display_name(self) -> str | None:
        return self.metadata.get("displayName")

    @property
    def short_display_name(self) -> str | None:
        return self.metadata.get("shortDisplayName")

    @property
    def description(self) -> str | None:
        return self.metadata.get("description")

    @property
    def origin(self) -> str | None:
        return self.metadata.get("origin")

    @property
    def source(self) -> str | None:
        return self.metadata.get("attributeSource")

    @property
    def scope(self) -> str | None:
        return self.metadata.get("scope")

    @property
    def auto_generated(self) -> bool | None:
        return self.metadata.get("autoGenerated")

    @property
    def column_type(self) -> str | None:
        return self.metadata.get("columnType")

    @property
    def pql(self) -> str | None:
        return self.metadata.get("pql")


@dataclass(frozen=True)
class GenericKnowledgeObject(KnowledgeObject):
    """A captured definition with no category-specific executable behavior."""


@dataclass(frozen=True)
class Record(KnowledgeObject):
    """Captured record definition, not a materialized data row."""

    def _query_attributes(self) -> Iterator[Attribute[Any]]:
        """Yield queryable attributes in each captured collection's order."""
        for key, name in (
            ("attributes", "attributes"),
            ("newAttributes", "new_attributes"),
            ("augmentedAttributes", "augmented_attributes"),
        ):
            namespace = getattr(self, name, None)
            if isinstance(namespace, Namespace):
                attributes = iter(namespace)
            else:
                attributes = (
                    Attribute(self.capture, (*self.path, key, index))
                    for index, item in enumerate(self.metadata.get(key) or ())
                    if isinstance(item, Mapping)
                    and item.get("type") in (None, "ATTRIBUTE")
                )
            for attribute in attributes:
                if (
                    isinstance(attribute, Attribute)
                    and isinstance(attribute.id, str)
                    and attribute.id.strip()
                    and isinstance(attribute.pql, str)
                    and attribute.pql.strip()
                ):
                    yield attribute


@dataclass(frozen=True)
class _Sortable(KnowledgeObject, Generic[T]):
    def asc(self) -> Sort:
        """Order this captured expression from low to high."""
        return Sort(self)

    def desc(self) -> Sort:
        """Order this captured expression from high to low."""
        return Sort(self, ascending=False)


@dataclass(frozen=True)
class Sort:
    """An ordering that retains the captured expression and its defaults."""

    expression: _Sortable[Any]
    ascending: bool = True


@dataclass(frozen=True)
class Attribute(_Sortable[T]):
    """Captured attribute with a declared value type, possibly nullable in data."""

    def eq(self, value: T | None) -> Predicate:
        """Compare with a Python value; None produces an IS NULL filter."""
        from celofast.expressions import Predicate

        return Predicate.equal(self, value)


@dataclass(frozen=True)
class KPI(_Sortable[T]):
    """Captured KPI, including its definition and associated metadata."""


@dataclass(frozen=True)
class Filter(KnowledgeObject):
    """Captured KM filter definition."""


@dataclass(frozen=True)
class Variable(KnowledgeObject, Generic[T]):
    """Captured variable definition and default, independent of input state."""


@dataclass(frozen=True)
class KnowledgeModel(KnowledgeObject):
    """Root of one complete generated KM capture."""

    _handle: KnowledgeModelHandle | None = field(
        default=None, kw_only=True, compare=False, repr=False
    )

    def _connect(self, handle: KnowledgeModelHandle) -> Self:
        """Return a connected copy, preserving this generated root's type."""
        handle.bind(self)
        return replace(self, _handle=handle)

    def _connection(self) -> KnowledgeModelHandle:
        if self._handle is None:
            raise RuntimeError("Connect this model with cf.km(model) first.")
        return self._handle

    @property
    def native(self) -> NativeKnowledgeModel:
        return self._connection().native

    @property
    def data_model(self) -> DataModel:
        return self._connection().data_model

    @property
    def augmentation_tables(self) -> AugmentationTableCollection:
        return self._connection().augmentation_tables

    def select(
        self,
        columns: Record | Mapping[str, str | Attribute[Any] | KPI[Any]] | None = None,
        /,
        **named_columns: str | Attribute[Any] | KPI[Any],
    ) -> Query:
        """Select a complete record, a mapping, or named output columns."""
        return self._connection().select(columns, **named_columns)

    def build(
        self,
        query: Mapping[str, object],
        *,
        variables: Mapping[str, str] | None = None,
    ) -> pql.PQL:
        """Compile an existing dictionary query without executing it."""
        return self._connection().build(query, variables=variables)

    def execute(
        self,
        query: Mapping[str, object],
        *,
        variables: Mapping[str, str] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        distinct: bool = False,
    ) -> pd.DataFrame:
        """Execute an existing dictionary query through the shared handle."""
        return self._connection().execute(
            query, variables=variables, limit=limit, offset=offset, distinct=distinct
        )

    @property
    def input_variables(self) -> Mapping[str, Any] | None:
        """Captured Studio defaults for inspection; execution remains native."""
        return self.capture.input_variables

    @property
    def key(self) -> str:
        return self.capture.source.key

    @property
    def mode(self) -> ResourceMode:
        return self.capture.source.mode


@dataclass(frozen=True)
class Namespace:
    """Generated collection with autocomplete, iteration, and exact-ID lookup."""

    capture: Capture
    path: Path
    _members: ClassVar[tuple[tuple[str | None, str], ...]] = ()

    def __iter__(self) -> Iterator[KnowledgeObject]:
        for _, name in self._members:
            yield getattr(self, name)

    def __len__(self) -> int:
        return len(self._members)

    def __getitem__(self, source_id: str) -> KnowledgeObject:
        matches = [name for id_, name in self._members if id_ == source_id]
        if len(matches) != 1:
            raise KeyError(source_id)
        return getattr(self, matches[0])
