"""Small immutable runtime shared by generated Knowledge Model packages."""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from typing import Any, ClassVar, Generic, TypeVar

from celofast.sdk.capture import Capture

T = TypeVar("T")
Path = tuple[str | int, ...]


@dataclass(frozen=True)
class KnowledgeObject:
    """A definition in one capture. Generated subclasses add concrete children."""

    capture: Capture
    path: Path = ()

    @property
    def metadata(self) -> Mapping[str, Any]:
        value: Any = self.capture.definition
        for segment in self.path:
            if isinstance(value, tuple) and isinstance(segment, str):
                matches = [
                    item
                    for item in value
                    if isinstance(item, Mapping) and item.get("id") == segment
                ]
                if len(matches) != 1:
                    raise KeyError(segment)
                value = matches[0]
            else:
                value = value[segment]
        return value

    @property
    def id(self) -> str | None:
        return self.metadata.get("id")

    @property
    def display_name(self) -> str | None:
        return self.metadata.get("displayName")

    @property
    def short_display_name(self) -> str | None:
        return self.metadata.get("shortDisplayName")

    @property
    def description(self) -> str | None:
        return self.metadata.get("description")

    @property
    def origin(self) -> str | None:
        return self.metadata.get("origin")

    @property
    def source(self) -> str | None:
        return self.metadata.get("attributeSource")

    @property
    def scope(self) -> str | None:
        return self.metadata.get("scope")

    @property
    def auto_generated(self) -> bool | None:
        return self.metadata.get("autoGenerated")

    @property
    def column_type(self) -> str | None:
        return self.metadata.get("columnType")

    @property
    def pql(self) -> str | None:
        return self.metadata.get("pql")


@dataclass(frozen=True)
class GenericKnowledgeObject(KnowledgeObject):
    """A captured definition with no category-specific executable behavior."""


@dataclass(frozen=True)
class Record(KnowledgeObject):
    """Captured record definition, not a materialized data row."""


@dataclass(frozen=True)
class Attribute(KnowledgeObject, Generic[T]):
    """Captured attribute with a declared value type, possibly nullable in data."""


@dataclass(frozen=True)
class KPI(KnowledgeObject, Generic[T]):
    """Captured KPI, including its definition and associated metadata."""


@dataclass(frozen=True)
class Filter(KnowledgeObject):
    """Captured KM filter definition."""


@dataclass(frozen=True)
class Variable(KnowledgeObject, Generic[T]):
    """Captured variable definition and default, independent of input state."""


@dataclass(frozen=True)
class KnowledgeModel(KnowledgeObject):
    """Root of one complete generated KM capture."""

    @property
    def key(self) -> str:
        return self.capture.source.key

    @property
    def mode(self) -> str:
        return self.capture.source.mode


@dataclass(frozen=True)
class Namespace:
    """Generated collection with autocomplete, iteration, and exact-ID lookup."""

    capture: Capture
    path: Path
    _members: ClassVar[tuple[tuple[str | None, str], ...]] = ()

    def __iter__(self) -> Iterator[KnowledgeObject]:
        for _, name in self._members:
            yield getattr(self, name)

    def __len__(self) -> int:
        return len(self._members)

    def __getitem__(self, source_id: str) -> KnowledgeObject:
        matches = [name for id_, name in self._members if id_ == source_id]
        if len(matches) != 1:
            raise KeyError(source_id)
        return getattr(self, matches[0])
